### ISSUE TITLE
Untranslatable app

### ISSUE THREAD

**Issue by ghost** [perryhelion/Hex-Explorer#1]
Hello,
Could you please make this app translatable?
Thanks for this great work!

**Comment by perryhelion** [comment]
Hello, my apologies for taking so long to reply to this email but I hadn't
been checking my mail for a while and only just found your message!

I thought that I had made the application program translatable by
using the *i18n.tr
http://i18n.tr("some text") *for any text part of the code, but will look
into what's needed for the program to be translatable.

Thanks for bringing this to my attention!

Kindest regards,
P Helion

**Comment by ghost** [comment]
Thank you.
I just don't know how to generate the .pot file.
After that, I can help for the French translation.

**Comment by perryhelion** [comment]
Hello Anne017,

My apologies for taking 4 months to put the .pot file up but finally here it is!

I've been holding off updating the application until there's enough changes to justify it, but if the next Ubuntu Phone OTA moves to a newer framework and there's some translations available then it would be worth doing, so there's no rush to get it done, but if you were still keen to help with the French translation then that'd be excellent. 

Thanks again for letting me know about the translation not being possible before.

Kindest regards,
P Helion

**Comment by perryhelion** [comment]
Hi Anne017, I (eventually) realised that the .pot file was sitting there
the whole time in the main project folder and have put it up on the
HexExplorer GitHub page.

I sent a message from GitHub but then closed the 'Issue' so not sure if you
received notification, but I think that's all that's needed to make
translating the app possible.

I've also got a new application up called 'sTOnSCipAP' which might be more
of a translating challenge than HexExplorer.
The .pot file has a lot more text (mostly from the 'How To Play' section) -
I think I'm probably meant to add a few more context hints to make it less
of a hassle to translate so let me know if there's anything missing that
would help.

Kindest regards,
P Helion

**Comment by ghost** [comment]
I indeed missed your fix and have just made a pull request (and also another one for sTOnSCipAP).
Hints are useful but the screenshots you published in the Software Center are even better, thanks ;)
